config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations' }
  # devise_for :users
  resources :spas

  root 'spa#index'
  #post "site/new" => 'spa#new_site'
  post "site/new" => 'spa#site_from_template'
  post "upload/site" => 'spa#upload_site'
  post "update/upload/site" => 'spa#update_uploaded_site'
  get "site/import" => 'spa#import_site'
  post "site/import" => 'spa#import_site'
  get "site/:dir" => 'sites#index'
  resources :sites, only: [] do
    get :download, on: :collection
    get :processing_status, on: :member
  end
  get "site/page/edit" => 'spa#page_editor'
  get "site/html" => 'spa#page_html'
  get "site/:site_id/pages" => 'spa#site_pages'
  post "site/pages" => 'spa#site_pages'
  post "sites/list" => 'spa#sites_collection'
  get "sites/list" => 'spa#sites_collection'
  post "site/delete" => 'spa#delete_site'
  post "site/publish" => 'spa#publish_site'
  post "site/unpublish" => 'spa#unpublish_site'
  post "site/save/meta" => 'spa#site_meta_update'
  get "site/pub/stats" => 'spa#publication_percentage_stats'
  post "site/duplicate", to: 'spa#duplicate_site'

  post "sites/:site_id/domains" => 'spa#domains_collection'
  get "sites/:site_id/domains" => 'spa#domains_collection'

  get "page/import" => 'spa#import_page'
  post "page/import" => 'spa#import_page'
  post "page/clone" => 'spa#clone_page'
  post "page/delete" => 'spa#delete_page'
  post "page/title/update" => 'spa#page_title_update'

  post "user/set_report_bucket" => "spa#user_set_report_bucket"
  get "user/test_report_setup" => "spa#user_test_report_setup"

  post "upload/images" => 'media#image_upload'
  get "images/list" => 'media#images_collection'
  post "images/list" => 'media#images_collection'
  get "images/array" => 'media#image_url_array'
  get "images/pagination" => 'media#images_pagination'
  get "images/page/:media_image_page" => 'media#images_page'
  post "image/delete/:image_id" => 'media#delete_image'
  post "page/image/delete" => 'media#delete_page_image'
  post "image/save/meta" => 'media#image_meta_update'

  post "upload/videos" => 'media#video_upload'
  get "videos/list" => 'media#videos_collection'
  post "videos/list" => 'media#videos_collection'
  get "videos/array" => 'media#video_url_array'
  get "videos/pagination" => 'media#videos_pagination'
  get "videos/page/:media_video_page" => 'media#videos_page'
  post "video/delete/:video_id" => 'media#delete_video'
  post "video/thumbnail/rotate" => 'media#rotate_video_thumbnail'
  post "video/save/meta" => 'media#video_meta_update'

  post "upload/audios" => 'media#audio_upload'
  get "audios/list" => 'media#audios_collection'
  post "audios/list" => 'media#audios_collection'
  get "audios/array" => 'media#audio_url_array'
  get "audios/pagination" => 'media#audios_pagination'
  get "audios/page/:media_audio_page" => 'media#audios_page'
  post "audio/delete/:audio_id" => 'media#delete_audio'
  post "audio/save/meta" => 'media#audio_meta_update'

  post "upload/files" => 'documents#file_upload'
  get "documents/files_render" => 'documents#files_render'
  get "documents/list" => 'documents#files_collection'
  post "documents/list" => 'documents#files_collection'
  get "documents/array" => 'documents#file_url_array'
  get "documents/pagination" => 'documents#files_pagination'
  get "documents/page/:media_document_page" => 'documents#files_page'
  post "document/delete/:document_id" => 'documents#delete_file'
  post "document/save/meta" => 'documents#document_meta_update'

  post "buckets/list", to: 'buckets#buckets_collection'
  get "buckets/list", to: 'buckets#buckets_collection'
  post "buckets/new", to: 'buckets#create'
  post "buckets/delete", to: 'buckets#destroy'
  get "buckets/pagination", to: 'buckets#buckets_pagination'
  get "buckets/page/:bucket_page", to: 'buckets#buckets_page'
  get "buckets/select/list", to: 'buckets#buckets_select_list'
  post "buckets/add", to: 'buckets#add_to_bucket'
  post "buckets/remove", to: 'buckets#remove_from_bucket'

  post "aws/new" => 'aws#create_credentials'
  get 'aws/connect_to_s3' => 'aws#connect_to_s3'
  post 'aws/test_credentials' => 'aws#test_credentials'
  get 'aws/configure_aws_automatically' => 'aws#configure_aws_automatically'
  get "bucket/status" => 'aws#bucket_status'

  get "site/:site_id/imported_data" => 'spa#imported_data'

  post "site/edit" => 'spa#save_edits'

  #post "/:site_token/visits" => 'analytics#visits'
  #post "/:site_token/events" => 'analytcs#events'

  # Analytics/tracking
  resources :domains
  match 'ahoy/visits', to: "visits#index", via: [:options]
  post 'ahoy/visits', to: "visits#index"
  resources :visits, only: [:index]
  match 'ahoy/events', to: "events#index", via: [:options]
  post 'ahoy/events', to: "events#index"
  resources :events, only: [:index]

  get '/tracking', to: 'tracking#tracking'
  post 'sites/create_or_update_domain' => 'spa#create_or_update_domain'
  get "sites/:id/delete_domain" => 'spa#delete_domain'
end

app/controllers/spa_controller.rb
require 'zip'

class SpaController < ApplicationController
  #before_action :set_spa, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  include SpasHelper
  # GET /spas
  # GET /spas.json
  def index
    @template_designs = TemplateDesign.all
    @templates = Template.all
    @sites = current_user.sites.paginate(page: params[:site_page], per_page: 10)
    if AmazonKey.where(user_id: current_user.id).count > 0
      @amazon_key = AmazonKey.find_by(user_id: current_user.id)
    else
      @amazon_key = nil
    end

    @sites_count = current_user.sites.count
    @sites_deployed = current_user.sites.where(mode: "published").count

    # New objects created for file uploads.
    @images = Image.new
    @videos = Video.new
    @audios = Audio.new
    @files = Document.new
    @site_upload = Site.new
    #@imports = Import.new

    # Retrieve the images, videos, and sound files for the media tab and dashboard.
    @site_images = Image.where(user_id: current_user.id)
    @site_videos = Video.where(user_id: current_user.id)
    @site_audios = Audio.where(user_id: current_user.id)
    @site_documents = Document.where(user_id: current_user.id)
    @site_buckets = Bucket.where(user_id: current_user.id).paginate(page: params[:bucket_page], per_page: 6).order(id: :desc)
    @user_files =  @site_images + @site_videos + @site_audios + @site_documents

    # Get the user-created buckets.
    @buckets = current_user.buckets.all

    @tutes = params[:category_id] ? Tute.where(category_id: params[:category_id]) : Tute.all
    @categories = Category.all

    @media_types = [
      ['audio', 'Audio'],
      ['video', 'Video'],
      ['image', 'Image'],
      ['other', 'Document']
    ]
  end

  def publication_percentage_stats
    @sites_count = current_user.sites.count
    @sites_deployed = current_user.sites.where(mode: "published").count

    unpub = @site_count.to_i - @site_deployed.to_i

    @chart_data = {
        value: unpub,
        color: "#46BFBD",
        highlight: "#5AD3D1",
        label: "Unpublished"
    },
    {
        value: @site_deployed,
        color: "#FDB45C",
        highlight: "#FFC870",
        label: "Published"
    }

    @chart_options = { width: 225 }

    render layout: false
  end

  def site_from_template
    site_params = JSON.parse(params["_json"])

    site = Site.new

    site.user_id = current_user.id
    site.template_id = site_params["template"]
    site.name = site_params["title"].gsub(/[^0-9a-z]/i, '').gsub(" ", "_").downcase
    site.label = site_params["title"]
    site.mode = "edit"
    site.generate_token("directory", 14)
    # Persist state to DB to replace websockets since they can't be used in Nginx/Unicorn.
    site.processing_event = "record"
    site.processing_msg = "<span class='fa fa-database'></span>&nbsp;&nbsp;Site recorded in database."
    site.save

    tmpl = Template.find(site.template_id)

    # render json: { message: "Site recorded in database.", status: "record", site_id: "#{site.id}", template_id: "#{site.template_id}", site_name: "#{site.name}", site_label: "#{site.label}", template_label: "#{tmpl.label}", template_thumbnail: "#{tmpl.thumbnail}", directory: "#{site.directory}", guid: "#{params[:guid]}" }, :status => 200
    #WebsocketRails[:site_events].trigger 'new_event', { message: "Site recorded in database.", status: "record", site_id: "#{site.id}", template_id: "#{site.template_id}", site_name: "#{site.name}", site_label: "#{site.label}", template_label: "#{tmpl.label}", template_thumbnail: "#{tmpl.thumbnail}", directory: "#{site.directory}", guid: "#{params[:guid]}" }

    Thread.new do
      #system "mkdir #{Rails.root}/public/sites/#{site.directory}"
      system "cp -R #{Rails.root}/lib/templates/files/#{tmpl.directory}  #{site.local_path}"

      # Build a list of pages for this site.
      find_html_files(site.id, site.local_path)

      # Persist state to DB to replace websockets since they can't be used in Nginx/Unicorn.
      site.processing_event = "editor"
      site.processing_msg = "<span class='fa fa-pencil-square-o'></span>&nbsp;&nbsp;Template-based site processed. Adding editing capability."
      site.save
      #WebsocketRails[:site_events].trigger 'new_event', { message: "Template-based site processed. Adding editing capability.", status: "editor", site_id: "#{site.id}", guid: "#{params[:guid]}" }

      # Added editor data to every page.
      pages = site.pages

      pages.each do |page|
        # Inject the editor into pages.
        EditabilityInjector.inject_editability(site.local_path, page.url, site.local_path, site.id, page.id)
      end

      # Persist state to DB to replace websockets since they can't be used in Nginx/Unicorn.
      site.processing_event = "complete"
      site.processing_msg = nil
      site.save
      #WebsocketRails[:site_events].trigger 'new_event', { message: "Site is complete.", status: "complete", site_id: "#{site.id}", guid: "#{params[:guid]}" }

      # Ensure DB connections are closed, as threads open their own.
      ActiveRecord::Base.connection.close
    end

    # Build our response
    resp_hash = { success: true, id: site.id, template_id: tmpl.id, template_label: tmpl.label, template_thumbnail: tmpl.thumbnail, created_at: site.created_at, directory: site.directory }
    render json: resp_hash, :status => 200
  end

  def upload_site
    aws_conn("bucketbox-sites-#{current_user.token}", nil)

    site = Site.new

    site.user_id = current_user.id
    site.template_id = 6
    site.name = "untitled"
    site.label = "Untitled"
    site.mode = "published"
    site.generate_token("directory", 14)
    site.upload = params[:file]
    # Write to DB since websockets don't work in Unicorn/Nginx
    site.processing_event = "record"
    site.processing_msg = "<span class='fa fa-database'></span>&nbsp;&nbsp;Site recorded in database."

    tmpl = Template.find(site.template_id)

    if site.save
      #WebsocketRails[:site_events].trigger 'new_event', { message: "Site recorded in database.", status: "record", site_id: "#{site.id}", template_id: "#{site.template_id}", site_name: "#{site.name}", site_label: "#{site.label}", template_label: "#{tmpl.label}", template_thumbnail: "#{tmpl.thumbnail}", directory: "#{site.directory}", guid: "#{params[:guid]}" }

      # render json: { message: "success" }, :status => 200

      Thread.new do
        # If the path 'tmp/zips/unique_directory' doesn't exist, create it.
        dirname = File.dirname("tmp/zips/#{site.directory}/#{site.upload_file_name}")
        unless File.directory?(dirname)
          FileUtils.mkdir_p(dirname)
        end

        # Download the .zip file.
        File.open("tmp/zips/#{site.directory}/#{site.upload_file_name}", 'wb') do |file|
          file << open("#{site.upload.url}").read

          # Write to DB since websockets don't work in Unicorn/Nginx
          site.processing_event = "processing"
          site.processing_msg = "<span class='fa fa-archive'></span>&nbsp;&nbsp;Processing uploaded .zip file."
          site.save
          #WebsocketRails[:site_events].trigger 'new_event', { message: "Processing uploaded .zip file.", status: "processing", site_id: "#{site.id}", guid: "#{params[:guid]}" }
        end

        # Unzip the attached .zip file.
        Zip::File.open("tmp/zips/#{site.directory}/#{site.upload_file_name}") { |zip_file|
             zip_file.each { |f|
                 f_path=File.join(site.local_path, f.name)
                 #f_path=File.join("tmp/sites/#{site.directory}", f.name)
             FileUtils.mkdir_p(File.dirname(f_path))
             zip_file.extract(f, f_path) unless File.exist?(f_path)
            }
        }

        # Write to DB since websockets don't work in Unicorn/Nginx
        site.processing_event = "editor"
        site.processing_msg = "<span class='fa fa-pencil-square-o'></span>&nbsp;&nbsp;Uploaded site processed. Adding editing capability."
        site.save
        # WebsocketRails[:site_events].trigger 'new_event', { message: "Uploaded site processed. Adding editing capability.", status: "editor", site_id: "#{site.id}", guid: "#{params[:guid]}" }

        # Check if the unzipped directory contains index.html or index.htm in the root.
        upload_file_name = site.upload_file_name.split(".")[0]

        unless site_index(site)
        #unless File.exists?("tmp/sites/#{site.directory}/#{upload_file_name}/index.html") || File.exists?("tmp/sites/#{site.directory}/#{upload_file_name}/index.htm") || File.exists?("tmp/sites/#{site.directory}/index.html") || File.exists?("tmp/sites/#{site.directory}/index.htm")
          puts "Deleting site - no index file in zip..."
          puts "#{site.local_path}/#{upload_file_name}"
          # Delete the .zip file.
          Dir.chdir("#{Rails.root}/tmp/zips") do
            system "rm -r #{site.directory}"
          end

          # Delete the site directory
          system "rm -r #{site.local_path}"

          # Delete the database record.sit
          site.destroy

          render :nothing => true, :status => 200, :content_type => 'text/html'
          # render json: { status: "error", message: "Zip file does not contain index.html or index.htm in root directory." }, :status => 200
        else
          puts "Index file exists, continuing on..."
          # Get the index file name/extension.
          if File.exists?("#{site.local_path}/#{upload_file_name}/index.html")
            puts "First: #{upload_file_name}"
            index_dir = site.local_path
            index_name = "index.html"

            # Move from the URL sub-directory to the site root.
            move_to_root_dir(site.id, "#{upload_file_name}")

          elsif File.exists?("#{site.local_path}/#{upload_file_name}/index.htm")
            puts "Second"
            index_dir = site.local_path
            # elsif File.exists?("tmp/sites/#{site.directory}/#{upload_file_name}/index.htm")
            # index_dir = "tmp/sites/#{site.directory}"

app/helpers/spas_helper.rb
module SpasHelper

  def random_div_id
    rand(1..10000)
  end


  def site_index(site)
    return 'index.html' if File.exists?("#{site.local_path}/index.html")
    return 'index.htm' if File.exists?("#{site.local_path}/index.htm")
  end

  def find_html_files(site_id, curr_directory)
    puts "Find pages..."
    site = Site.find(site_id)

    Dir.chdir("#{curr_directory}") do
      html_files = Dir.glob("**/*.html")

      html_files.each do |file|
        puts "Writing to DB: #{file}"
        filename = file.split("/").pop

        title_html = Nokogiri::HTML( File.open(file) )
        title = title_html.css("title").text.to_s.truncate(100)

        page = site.pages.new

        page.site_id = site_id
        page.name = filename
        page.label = title
        page.url = file
        page.page = true
        page.save
      end
    end
  end
end

app/views/spa/index.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-12">
          <div class="fs-panel panel-default">
              <div class="panel-heading">
                  <div class="row-fluid user-row inline-head">
                      <%= image_tag "title_logo.png", class: "fs-img-responsive", alt: "BucketBox Login", style: "height: 50px;" %>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                      <i class="fa fa-sign-out fa-3x"></i>
                      <% end %>
                      <a href="#domains" aria-controls="domains" role="pill" data-toggle="tab">
                        <i class="fa fa-life-ring fa-3x"></i>
                      </a>
                      <div class="pull-right-user">
                        <ul class="nav nav-pills">
                          <li role="presentation" class="dropdown" data-toggle="tooltip" data-placement="bottom" title="Edit profile">
                            <a data-toggle="dropdown" href="#" class="dropdown-toggle"><i class="fa fa-user fa-3x"></i>&nbsp;</a>
                            <div class="dropdown-menu dropdown-menu-right" style="padding: 15px; padding-bottom: 0px;">
                              <!-- Profile editor -->
                              <div class="container" style="padding-top: 30px; width: 600px;">
                                <h2 class="page-header">Edit Profile</h2>
                                <div class="row">
                                  <div class="col-md-12 col-sm-6 col-xs-12 personal-info">
                                    <!-- <div class="alert alert-info alert-dismissable">
                                      <a class="panel-close close" data-dismiss="alert">×</a>
                                      <i class="fa fa-coffee"></i>
                                      This is an <strong>.alert</strong>. Use this to show important messages to the user.
                                    </div> -->
                                    <div class="row">
                                      <div class="col-md-12">
                                        <div class="panel panel-default">
                                          <div class="panel-heading">Profile</div>
                                          <div class="panel-body">
                                            <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
                                              <%= devise_error_messages! %>

                                              <div class="field">
                                                <%= f.label :first_name %><br />
                                                <%= f.text_field :first_name, :class => "form-control", autofocus: true, value: current_user.first_name %>
                                              </div>

                                              <div class="field">
                                                <%= f.label :last_name %><br />
                                                <%= f.text_field :last_name, :class => "form-control", autofocus: false, value: current_user.last_name %>
                                              </div>

                                              <div class="field">
                                                <%= f.label :email %><br />
                                                <%= f.email_field :email, :class => "form-control", autofocus: false, value: current_user.email %>
                                              </div>

                                              <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
                                                <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
                                              <% end %>

                                              <div class="field">
                                                <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
                                                <%= f.password_field :password, :class => "form-control", autocomplete: "off" %>
                                              </div>

                                              <div class="field">
                                                <%= f.label :password_confirmation %><br />
                                                <%= f.password_field :password_confirmation, :class => "form-control", autocomplete: "off" %>
                                              </div>

                                              <div class="field">
                                                <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
                                                <%= f.password_field :current_password, :class => "form-control", autocomplete: "off" %>
                                              </div>

                                              <div class="actions">
                                                <%= f.submit "Save Changes", class: "btn btn-primary pull-right" %>
                                              </div>
                                            <% end %>
                                          </div>
                                        </div>
                                      </div>

                                      <div class="col-md-12">
                                        <div class="panel panel-default">
                                          <div class="panel-heading">Unhappy with BucketBox?</div>
                                          <div class="panel-body">
                                            <p>We would hate to see you go, but you can cancel your account at any time by clicking the button below:</p>
                                            <%= button_to "Cancel my account", registration_path(resource_name), class: "btn btn-primary pull-right", data: { confirm: "Are you sure?" }, method: :delete %>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              <!-- End profile editor -->
                              </div>
                            </div>
                          </li>

                          <!--li role="presentation"><a href="/app"><i class="fa fa-power-off"></i></a></li-->
                        </ul>
                      </div>
                  </div>
              </div>
              <div class="panel-body">
                <div role="tabpanel">
                    <div class="pull-right">
                      <a href="#cloud" aria-controls="cloud" role="pill" data-toggle="tab">
                      <i class="fa fa-cog fa-4x"></i>
                      </a>
                    </div>
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist" id="tab_links">
                      <li role="presentation" class="active"><a href="#home" aria-controls="home" role="pill" data-toggle="tab"><div class="panel-elements"><i class="fa fa-align-justify fa-2x"></i>&nbsp;<span>DASHBOARD</span></div></a></li>
                      <li role="presentation"><a href="#buckets" aria-controls="profile" role="pill" data-toggle="tab"><div class="panel-elements"><i class="fa fa-folder-open fa-2x"></i>&nbsp;<span>BUCKETS</span></div></a></li>
                      <li role="presentation"><a href="#files" aria-controls="profile" role="pill" data-toggle="tab"><div class="panel-elements"><i class="fa fa-file fa-2x"></i>&nbsp;<span>FILES</span></div></a></li>
                      <li role="presentation"><a href="#sites" aria-controls="site" role="pill" data-toggle="tab"><div class="panel-elements"><i class="fa fa-desktop fa-2x"></i>&nbsp;<span>SITES</span></div></a></li>
                      <li role="presentation" class=""><a href="#tutes" aria-controls="tutes" role="pill" data-toggle="tab"><div class="panel-elements"><i class="fa fa-play-circle fa-2x"></i>&nbsp;<span>TUTES</span></div></a></li>
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                      <div role="tabpanel" class="tab-pane active" id="home">
                        <%= render "partials/dashboard" %>
                      </div>

                      <!-- Media management -->
                      <div role="tabpanel" class="tab-pane" id="media">
                        <%= render "partials/media" %>
                      </div>
                      <!-- END media management -->

                      <!-- Bucket management -->
                      <div role="tabpanel" class="tab-pane" id="buckets">
                        <%= render "partials/buckets" %>
                      </div>
                      <!-- END bucket management -->

                      <!-- File management -->
                      <div role="tabpanel" class="tab-pane" id="files">
                        <%= render "partials/files" %>
                      </div>
                      <!-- END file management -->

                      <!-- Domain name management -->
                      <div role="tabpanel" class="tab-pane" id="domains">
                        <%= render "partials/domains" %>
                      </div>
                      <!-- END domain name management -->

                      <!-- Site management -->
                      <div role="tabpanel" class="tab-pane" id="sites">
                        <%= render "partials/sites" %>
                      </div>
                      <!-- END site management -->

                      <!-- Amazon S3 settings management -->
                      <div role="tabpanel" class="tab-pane" id="tutes">
                        <%= render "partials/tutes" %>
                      </div>

                      <div role="tabpanel" class="tab-pane" id="cloud">
                        <%= render "partials/cloud" %>
                      </div>
                      <!-- END Amazon S3 settings management -->
                    </div>
                </div>
              </div>
          </div>
      </div>
  </div>
</div>

<!-- Modals -->
<% if @amazon_key.blank? %>
<div class="modal" id="aws_credentials_modal" tabindex="-1" role="dialog" aria-labelledby="awsCredentialsModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="awsCredentialsModalLabel">Welcome to BucketBox!</h4>
      </div>
      <div class="modal-body">
        BucketBox has been designed from the ground up to make it as dead easy as possible to push your websites to Amazon's S3 file hosting service.<p/>
        Let's get started! The first thing you'll need to do is to enter your <strong>access key</strong> and <strong>secret access key</strong> so BucketBox can connect to your S3 account.<p/>
        Need more information on how to do that? Amazon's official description <a href="#"><em>can be found here</em></a>.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function(){
    $("#aws_credentials_modal").modal("show");

    $("#tab_links a[href='#cloud']").tab("show");

    $("[href='#home']").attr("data-toggle", "");
    $("[href='#media']").attr("data-toggle", "");
    $("[href='#domains']").attr("data-toggle", "");
    $("[href='#sites']").attr("data-toggle", "");
  });
</script>
<% end %>
<!-- End modals. -->

app/views/spa/index.js.erb
$('#tutes_render_collection').html("<%= j render partial: 'partials/tutes_list' %>")

app/views/spa/page_editor.html.erb
<!-- When the page is built, remove this page. Don't forget about routes! -->
<%= render "partials/page_editor", layout: false %>

app/views/spa/publication_percentage_stats.html.erb
<% unless @sites_count === 0 %>
    <div style="text-align: center; vertical-align: top;"><h3><%= @sites_count %> <%=  @sites_count > 1 ? "sites" : "site" %>.</h3></div>
    <div style="text-align: center; vertical-align: top;"><h3><%= @sites_count - @sites_deployed < @sites_count ? "#{((@sites_deployed.to_f / @sites_count.to_f )*100).to_i}%" : "No sites" %> published.</h3></div>
    <%= pie_chart({"Unpublished" => @sites_count - @sites_deployed, "Published" => @sites_deployed}, width: "210px") %>
<% else %>
    <p>You haven't added any sites to BucketBox yet.</p>
<% end %>